### ISSUE TITLE
Missing sequences

### ISSUE THREAD

**Issue by povlhp** [gm9/ingress-glyph-tools#4]
missing sequences observed on L7 portals:
PORTAL HAVE TRUTH DATA
TRAVEL NOT IMPROVE SOUL

I have started screen recording my fast hacks tour on local farm

**Comment by gm9** [comment]
Thank you for reporting the issue. I have fixed two sequences.
https://github.com/gm9/ingress-glyph-tools/commit/674bffe403d3767c829d358ed99b0357e88ba848
